sudo: false
language: android
android:
  components:
  - platform-tools
  - extra
  - android-21
  - build-tools-22.0.1
script:
- gradle clean build
notifications:
  slack:
    secure: Lt5Z5ejxI3mAPjBn0Drulvh/uFADuu8vhsQFB+3Wykjo0NlBEIpmO5CuGLbZi3umJDOFPU9XRkhuCF/C3qag4r6/YDS0Wl+CApbAxv7WUie1pqpMqGw4ZR3wrTZkDXzZB2crZUvnYi+K6+5ZtLAvY1ym4TloBMW3bSVZ2QxujxI=
  email:
    recipients:
    - jak@microsoft.com
    on_success: never
    on_failure: always
